import type { MetadataQueryAdmin } from '@/types/metadataManagement'
import { useTranslation } from 'react-i18next'

interface Props { queries: MetadataQueryAdmin[]; onEdit: (query: MetadataQueryAdmin) => void; onToggle: (query: MetadataQueryAdmin) => void; onDelete: (query: MetadataQueryAdmin) => void }
const head = 'border-b border-r border-slate-200 bg-slate-100 px-3 py-2 text-left text-xs font-semibold text-slate-600 dark:border-slate-700 dark:bg-slate-950 dark:text-slate-300'
const cell = 'border-b border-r border-slate-200 px-3 py-2 text-sm dark:border-slate-700'

export function QueryGrid({ queries, onEdit, onToggle, onDelete }: Props) {
  const { t } = useTranslation()
  return <div className="min-h-0 flex-1 overflow-auto border border-slate-200 dark:border-slate-700"><table className="w-full min-w-[980px] border-separate border-spacing-0"><thead className="sticky top-0 z-10"><tr><th className={head}>{t('queryManagement.queryCode')}</th><th className={head}>{t('queryManagement.queryName')}</th><th className={head}>{t('queryManagement.description')}</th><th className={head}>{t('queryManagement.status')}</th><th className={head}>{t('queryManagement.reference')}</th><th className={head}>Updated</th><th className={`${head} w-48`}>{t('queryManagement.actions')}</th></tr></thead><tbody>{queries.map((query) => <tr key={query.queryCode} className="bg-white text-slate-800 hover:bg-slate-50 dark:bg-slate-900 dark:text-slate-100 dark:hover:bg-slate-800"><td className={`${cell} font-mono font-semibold`}>{query.queryCode}</td><td className={cell}>{query.queryName}</td><td className={`${cell} max-w-[260px] truncate`}>{query.queryDescription || '-'}</td><td className={cell}><span className={query.enabled ? 'text-emerald-600' : 'text-slate-500'}>{query.enabled ? t('queryManagement.active') : t('queryManagement.inactive')}</span></td><td className={cell}>{query.referenceCount > 0 ? `${query.referenceCount}` : '-'}</td><td className={cell}>{query.updatedAt ? new Date(query.updatedAt).toLocaleString() : '-'}</td><td className={`${cell} space-x-2 whitespace-nowrap`}><button type="button" className="text-blue-600 hover:underline" onClick={() => onEdit(query)}>{t('queryManagement.edit')}</button><button type="button" className="text-slate-600 hover:underline dark:text-slate-300" onClick={() => onToggle(query)}>{query.enabled ? t('queryManagement.deactivate') : t('queryManagement.activate')}</button><button type="button" disabled={query.referenceCount > 0} className="text-rose-600 disabled:cursor-not-allowed disabled:opacity-40" onClick={() => onDelete(query)}>{t('queryManagement.delete')}</button></td></tr>)}{queries.length === 0 ? <tr><td colSpan={7} className="p-12 text-center text-sm text-slate-500">{t('queryManagement.empty')}</td></tr> : null}</tbody></table></div>
}
