import { useState } from 'react'
import type { UserAccount, UserDangerAction } from '@/types/userManagement'

interface UserDangerDialogProps { user: UserAccount; onClose: () => void; onSubmit: (action: UserDangerAction, keepPersonalization: boolean) => Promise<void> }

export function UserDangerDialog({ user, onClose, onSubmit }: UserDangerDialogProps) {
  const [action, setAction] = useState<UserDangerAction>('disable')
  const [keepPersonalization, setKeepPersonalization] = useState(true)
  const [saving, setSaving] = useState(false)
  const submit = async () => { setSaving(true); try { await onSubmit(action, keepPersonalization) } finally { setSaving(false) } }
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/60 p-4"><div className="w-full max-w-lg rounded-xl bg-white p-6 shadow-2xl dark:bg-slate-800"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-rose-600">위험 동작</p><h2 className="mt-1 text-xl font-bold text-slate-900 dark:text-white">{user.displayName} 계정 상태 관리</h2></div><button type="button" onClick={onClose} className="text-2xl text-slate-400" aria-label="닫기">×</button></div><p className="mt-4 rounded-md bg-amber-50 p-3 text-sm text-amber-900 dark:bg-amber-950/30 dark:text-amber-100">계정 삭제보다 비활성화 또는 퇴사 처리를 우선하세요. 역할, 개인화 설정, 이력 참조에 영향을 줄 수 있습니다.</p><div className="mt-5 space-y-2"><label className="flex gap-3 rounded-md border border-slate-200 p-3 dark:border-slate-700"><input type="radio" checked={action === 'disable'} onChange={() => setAction('disable')} /> <span><strong>계정 비활성화</strong><small className="block text-slate-500">로그인할 수 없도록 처리합니다.</small></span></label><label className="flex gap-3 rounded-md border border-slate-200 p-3 dark:border-slate-700"><input type="radio" checked={action === 'retire'} onChange={() => setAction('retire')} /> <span><strong>퇴사 처리</strong><small className="block text-slate-500">재직 상태를 퇴사로 변경합니다.</small></span></label><label className="flex gap-3 rounded-md border border-rose-200 p-3 dark:border-rose-900"><input type="radio" checked={action === 'delete-request'} onChange={() => setAction('delete-request')} /> <span><strong className="text-rose-700 dark:text-rose-200">삭제 요청</strong><small className="block text-slate-500">실제 삭제 대신 삭제 요청 상태로 기록합니다.</small></span></label></div>{user.personalization.hasSettings && <label className="mt-4 flex items-center gap-2 text-sm text-slate-700 dark:text-slate-200"><input type="checkbox" checked={keepPersonalization} onChange={(event) => setKeepPersonalization(event.target.checked)} /> 개인화 설정 유지 ({user.personalization.cameraGridCount}개 그리드)</label>}<div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-md border border-slate-300 px-4 py-2 text-sm dark:border-slate-600 dark:text-white">취소</button><button type="button" onClick={submit} disabled={saving} className="rounded-md bg-rose-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? '처리 중...' : '처리하기'}</button></div></div></div>
}
