-- Development master data for the M26 user and authorization model.

INSERT INTO TB_M26_AUTH (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    AUTH_CODE, AUTH_NAME, AUTH_TYPE, AUTH_DESCRIPTION, REMARKS
) VALUES
    ('S', 'SYSTEM', 'V003_SEED', 'S', 'SYSTEM', 'V003_SEED', 'ADMIN', 'Administrator', 'SYSTEM', 'Administrator role', 'Initial administrator role'),
    ('S', 'SYSTEM', 'V003_SEED', 'S', 'SYSTEM', 'V003_SEED', 'USER', 'User', 'SYSTEM', 'Default user role', 'Initial user role');

INSERT INTO TB_M26_USER (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    USER_EMP_NO, USER_NAME, ENCRYPTED_FOUNDATION_PASSWORD, REMARKS
) VALUES (
    'S', 'SYSTEM', 'V003_SEED',
    'S', 'SYSTEM', 'V003_SEED',
    'admin', 'Admin', '$2a$10$ycTLBxejOqApKaHo.tprruQbXV1qmuBWnxeeAZr8LBUqAscDY17TS', 'Development administrator'
);

INSERT INTO TB_M26_USER_AUTH (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    USER_ID, AUTH_ID, GRANT_START_DT, GRANT_END_DT, REMARKS
)
SELECT 'S', 'SYSTEM', 'V003_SEED', 'S', 'SYSTEM', 'V003_SEED',
       u.USER_ID, auth.AUTH_ID, '20260101', NULL, 'Development administrator authorization'
FROM TB_M26_USER u
JOIN TB_M26_AUTH auth ON auth.AUTH_CODE = 'ADMIN'
WHERE u.USER_EMP_NO = 'admin';
