-- Application branding labels managed through common codes.
-- Common code detail display names are expanded for Korean/English labels.

ALTER TABLE TB_M26_CODE_DETAIL
    ADD COLUMN IF NOT EXISTS CODE_VALUE_NAME_KO VARCHAR(100) DEFAULT NULL COMMENT 'Korean display name' AFTER CODE_VALUE_NAME;

ALTER TABLE TB_M26_CODE_DETAIL
    ADD COLUMN IF NOT EXISTS CODE_VALUE_NAME_EN VARCHAR(100) DEFAULT NULL COMMENT 'English display name' AFTER CODE_VALUE_NAME_KO;

INSERT INTO TB_M26_CODE (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    CODE_NAME, CODE_DESCRIPTION, CODE_TYPE, REMARKS
)
SELECT
    'S', 'SYSTEM', 'V008_SEED',
    'S', 'SYSTEM', 'V008_SEED',
    'APP_BRANDING', 'Application branding labels', 'SYSTEM', 'Header and sidebar title labels'
WHERE NOT EXISTS (
    SELECT 1 FROM TB_M26_CODE WHERE UPPER(CODE_NAME) = 'APP_BRANDING'
);

INSERT INTO TB_M26_CODE_DETAIL (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    CODE_ID, CODE_VALUE, CODE_VALUE_NAME, CODE_VALUE_NAME_KO, CODE_VALUE_NAME_EN,
    CODE_VALUE_DESCRIPTION, SORT_ORDER, REMARKS
)
SELECT
    'S', 'SYSTEM', 'V008_SEED',
    'S', 'SYSTEM', 'V008_SEED',
    c.CODE_ID, seed.CODE_VALUE, seed.CODE_VALUE_NAME_KO, seed.CODE_VALUE_NAME_KO, seed.CODE_VALUE_NAME_EN,
    seed.CODE_VALUE_DESCRIPTION, seed.SORT_ORDER, 'Application branding seed'
FROM TB_M26_CODE c
JOIN (
    SELECT 'APP_TITLE' AS CODE_VALUE, 'AI 영상통합 플랫폼' AS CODE_VALUE_NAME_KO, 'AI Video Integration Platform' AS CODE_VALUE_NAME_EN, 'Application title' AS CODE_VALUE_DESCRIPTION, 10 AS SORT_ORDER
    UNION ALL SELECT 'APP_SUBTITLE', '포항 4선재', 'Pohang Wire No.4', 'Application subtitle', 20
) seed
WHERE UPPER(c.CODE_NAME) = 'APP_BRANDING'
  AND NOT EXISTS (
      SELECT 1
      FROM TB_M26_CODE_DETAIL d
      WHERE d.CODE_ID = c.CODE_ID
        AND UPPER(d.CODE_VALUE) = seed.CODE_VALUE
        AND d.DATA_END_STATUS = 'N'
  );
