-- Add the middle-tier manager authorization between ADMIN and USER.

INSERT INTO TB_M26_AUTH (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    AUTH_CODE, AUTH_NAME, AUTH_TYPE, AUTH_DESCRIPTION, REMARKS
)
SELECT 'S', 'SYSTEM', 'V009_SEED', 'S', 'SYSTEM', 'V009_SEED',
       'MANAGER', 'Manager', 'SYSTEM', 'Manager role', 'Middle-tier manager role'
WHERE NOT EXISTS (
    SELECT 1
    FROM TB_M26_AUTH
    WHERE UPPER(AUTH_CODE) = 'MANAGER'
);
