-- Vision Monitor - Master tables.
-- User accounts and layout data are managed by TB_M26_USERS and TB_M26_LAYOUTS.

CREATE TABLE IF NOT EXISTS TB_M26_CODE (
    created_object_type VARCHAR(1) DEFAULT NULL,
    created_object_id VARCHAR(22) DEFAULT NULL,
    created_program_id VARCHAR(22) DEFAULT NULL,
    created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_updated_object_type VARCHAR(1) DEFAULT NULL,
    last_updated_object_id VARCHAR(22) DEFAULT NULL,
    last_updated_program_id VARCHAR(22) DEFAULT NULL,
    last_updated_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CODE_ID INT(15) UNSIGNED NOT NULL AUTO_INCREMENT,
    CODE_NAME VARCHAR(50) DEFAULT NULL,
    CODE_DESCRIPTION VARCHAR(120) DEFAULT NULL,
    CODE_TYPE VARCHAR(20) DEFAULT NULL,
    REMARKS VARCHAR(4000) DEFAULT NULL,

    PRIMARY KEY (CODE_ID),
    INDEX idx_tb_m26_code_type (CODE_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS TB_M26_CODE_DETAIL (
    created_object_type VARCHAR(1) DEFAULT NULL,
    created_object_id VARCHAR(22) DEFAULT NULL,
    created_program_id VARCHAR(22) DEFAULT NULL,
    created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_updated_object_type VARCHAR(1) DEFAULT NULL,
    last_updated_object_id VARCHAR(22) DEFAULT NULL,
    last_updated_program_id VARCHAR(22) DEFAULT NULL,
    last_updated_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    CODE_DETAIL_ID INT(15) UNSIGNED NOT NULL AUTO_INCREMENT,
    CODE_ID INT(15) UNSIGNED NOT NULL,
    CODE_VALUE VARCHAR(30) DEFAULT NULL,
    CODE_VALUE_NAME VARCHAR(100) DEFAULT NULL,
    CODE_VALUE_DESCRIPTION VARCHAR(1000) DEFAULT NULL,
    SORT_ORDER INT(2) DEFAULT NULL,
    DEFAULT_VALUE VARCHAR(30) DEFAULT NULL,
    REMARKS VARCHAR(4000) DEFAULT NULL,

    PRIMARY KEY (CODE_DETAIL_ID),
    CONSTRAINT fk_tb_m26_code_detail_code
        FOREIGN KEY (CODE_ID) REFERENCES TB_M26_CODE(CODE_ID) ON DELETE CASCADE,
    INDEX idx_tb_m26_code_detail_code_id (CODE_ID),
    UNIQUE INDEX uidx_tb_m26_code_detail_value (CODE_ID, CODE_VALUE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS TB_M26_AUTH (
    created_object_type VARCHAR(1) DEFAULT NULL,
    created_object_id VARCHAR(22) DEFAULT NULL,
    created_program_id VARCHAR(22) DEFAULT NULL,
    created_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    last_updated_object_type VARCHAR(1) DEFAULT NULL,
    last_updated_object_id VARCHAR(22) DEFAULT NULL,
    last_updated_program_id VARCHAR(22) DEFAULT NULL,
    last_updated_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    AUTH_ID INT(15) UNSIGNED NOT NULL AUTO_INCREMENT,
    AUTH_CODE VARCHAR(30) NOT NULL,
    AUTH_NAME VARCHAR(100) DEFAULT NULL,
    AUTH_TYPE VARCHAR(20) DEFAULT NULL,
    AUTH_DESCRIPTION VARCHAR(1000) DEFAULT NULL,
    REMARKS VARCHAR(4000) DEFAULT NULL,

    PRIMARY KEY (AUTH_ID),
    UNIQUE INDEX uidx_tb_m26_auth_code (AUTH_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
