-- Move legacy lowercase application tables to TB_M26_* physical tables.
-- Flyway runs before Hibernate validation, so the application must only see TB_M26_* tables after this migration.

CREATE TABLE IF NOT EXISTS TB_M26_CAMERAS LIKE cameras;
INSERT IGNORE INTO TB_M26_CAMERAS SELECT * FROM cameras;

CREATE TABLE IF NOT EXISTS TB_M26_STREAMS LIKE streams;
INSERT IGNORE INTO TB_M26_STREAMS SELECT * FROM streams;

CREATE TABLE IF NOT EXISTS TB_M26_EVENTS LIKE events;
INSERT IGNORE INTO TB_M26_EVENTS SELECT * FROM events;

CREATE TABLE IF NOT EXISTS TB_M26_RECORDINGS LIKE recordings;
INSERT IGNORE INTO TB_M26_RECORDINGS SELECT * FROM recordings;

CREATE TABLE IF NOT EXISTS TB_M26_ALERT_SETTINGS LIKE alert_settings;
INSERT IGNORE INTO TB_M26_ALERT_SETTINGS SELECT * FROM alert_settings;

CREATE TABLE IF NOT EXISTS TB_M26_LAYOUTS LIKE layouts;
INSERT IGNORE INTO TB_M26_LAYOUTS SELECT * FROM layouts;

CREATE TABLE IF NOT EXISTS TB_M26_ORG_UNITS LIKE org_units;
INSERT IGNORE INTO TB_M26_ORG_UNITS SELECT * FROM org_units;

CREATE TABLE IF NOT EXISTS TB_M26_USERS LIKE users;
INSERT IGNORE INTO TB_M26_USERS SELECT * FROM users;

DROP TABLE IF EXISTS alert_settings;
DROP TABLE IF EXISTS recordings;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS streams;
DROP TABLE IF EXISTS layouts;
DROP TABLE IF EXISTS org_units;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS cameras;
