INSERT INTO TB_M26_METADATA_QUERY (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    QUERY_CODE, QUERY_NAME, QUERY_DESCRIPTION, SQL_TEXT, RESULT_SCHEMA,
    QUERY_TIMEOUT_SEC, USE_STATUS, DATA_END_STATUS
)
SELECT 'S', 'SYSTEM', 'MIGRATION', 'S', 'SYSTEM', 'MIGRATION',
       'camera.connection-status', 'Camera Connection Status', 'Default connection status query',
       'SELECT VIDEO_SOURCE_ID AS sourceId, STATUS AS status FROM TB_M26_VIDEO_SOURCE WHERE VIDEO_SOURCE_ID = :sourceId AND DATA_END_STATUS = ''N''',
       '[{"name":"sourceId","label":"Source ID","type":"number"},{"name":"status","label":"Status","type":"string"}]',
       5, 'Y', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_M26_METADATA_QUERY WHERE QUERY_CODE = 'camera.connection-status');

INSERT INTO TB_M26_METADATA_QUERY (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    QUERY_CODE, QUERY_NAME, QUERY_DESCRIPTION, SQL_TEXT, RESULT_SCHEMA,
    QUERY_TIMEOUT_SEC, USE_STATUS, DATA_END_STATUS
)
SELECT 'S', 'SYSTEM', 'MIGRATION', 'S', 'SYSTEM', 'MIGRATION',
       'camera.recent-events', 'Recent Camera Events', 'Default recent event query',
       'SELECT 1 AS eventId, ''Mock event'' AS title WHERE :sourceId IS NOT NULL',
       '[{"name":"eventId","label":"Event ID","type":"number"},{"name":"title","label":"Title","type":"string"}]',
       5, 'Y', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_M26_METADATA_QUERY WHERE QUERY_CODE = 'camera.recent-events');

INSERT INTO TB_M26_VIDEO_METADATA_PROFILE (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    VIDEO_SOURCE_ID, PROFILE_NAME, DEFAULT_STATUS, USE_STATUS, DATA_END_STATUS
)
SELECT 'S', 'SYSTEM', 'MIGRATION', 'S', 'SYSTEM', 'MIGRATION', 2, 'Default Camera Profile', 'Y', 'Y', 'N'
WHERE NOT EXISTS (
    SELECT 1 FROM TB_M26_VIDEO_METADATA_PROFILE
    WHERE VIDEO_SOURCE_ID = 2 AND USE_STATUS = 'Y' AND DATA_END_STATUS = 'N'
);

INSERT INTO TB_M26_VIDEO_METADATA_SECTION (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    METADATA_PROFILE_ID, SECTION_CODE, SECTION_TITLE, SECTION_TYPE,
    SORT_ORDER, VISIBLE_STATUS, METADATA_QUERY_ID, REFRESH_INTERVAL_SEC,
    DEFAULT_TEXT, DATA_END_STATUS
)
SELECT 'S', 'SYSTEM', 'MIGRATION', 'S', 'SYSTEM', 'MIGRATION',
       p.METADATA_PROFILE_ID, 'connection', 'Connection Status', 'TEXT',
       0, 'Y', q.METADATA_QUERY_ID, 10, 'Connection status unavailable', 'N'
FROM TB_M26_VIDEO_METADATA_PROFILE p
JOIN TB_M26_METADATA_QUERY q ON q.QUERY_CODE = 'camera.connection-status'
WHERE p.VIDEO_SOURCE_ID = 2 AND p.USE_STATUS = 'Y' AND p.DATA_END_STATUS = 'N'
  AND NOT EXISTS (
      SELECT 1 FROM TB_M26_VIDEO_METADATA_SECTION s
      WHERE s.METADATA_PROFILE_ID = p.METADATA_PROFILE_ID
        AND s.SECTION_CODE = 'connection' AND s.DATA_END_STATUS = 'N'
  );
