ALTER TABLE TB_M26_VIDEO_METADATA_SECTION
    ADD COLUMN TEXT_DISPLAY_MODE VARCHAR(20) NOT NULL DEFAULT 'FREE' AFTER SECTION_TYPE;

CREATE INDEX IX_M26_METADATA_SECTION_TEXT_MODE
    ON TB_M26_VIDEO_METADATA_SECTION (SECTION_TYPE, TEXT_DISPLAY_MODE, DATA_END_STATUS);
