-- Development/demo login account. The password is tester123 (BCrypt).
INSERT INTO TB_M26_USER (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    USER_EMP_NO, USER_NAME, ENCRYPTED_FOUNDATION_PASSWORD, REMARKS
)
SELECT 'S', 'SYSTEM', 'V014_SEED', 'S', 'SYSTEM', 'V014_SEED',
       'tester', 'Demo Tester', '$2a$10$xdJ6WMGd1E2F0gkA/JSkD.iURIL4iU4u7uW5UolpUz8H6Fm55/x4G',
       'Development/demo administrator account'
WHERE NOT EXISTS (
    SELECT 1 FROM TB_M26_USER WHERE USER_EMP_NO = 'tester'
);

INSERT INTO TB_M26_USER_AUTH (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    USER_ID, AUTH_ID, GRANT_START_DT, GRANT_END_DT, REMARKS
)
SELECT 'S', 'SYSTEM', 'V014_SEED', 'S', 'SYSTEM', 'V014_SEED',
       u.USER_ID, auth.AUTH_ID, '20260101', NULL, 'Development/demo administrator authorization'
FROM TB_M26_USER u
JOIN TB_M26_AUTH auth ON auth.AUTH_CODE = 'ADMIN'
WHERE u.USER_EMP_NO = 'tester'
  AND NOT EXISTS (
      SELECT 1
      FROM TB_M26_USER_AUTH existing
      WHERE existing.USER_ID = u.USER_ID
        AND existing.AUTH_ID = auth.AUTH_ID
        AND existing.DATA_END_STATUS = 'N'
  );
