INSERT INTO TB_M26_CODE (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    CODE_NAME, CODE_DESCRIPTION, CODE_TYPE, REMARKS, DATA_END_STATUS
)
SELECT 'S', 'SYSTEM', 'V016_SEED', 'S', 'SYSTEM', 'V016_SEED',
       'PROCESS_AREA', 'Model process area', 'SYSTEM', 'Model management process areas', 'N'
WHERE NOT EXISTS (SELECT 1 FROM TB_M26_CODE WHERE UPPER(CODE_NAME) = 'PROCESS_AREA');

INSERT INTO TB_M26_CODE_DETAIL (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    CODE_ID, CODE_VALUE, CODE_VALUE_NAME, CODE_VALUE_NAME_KO, CODE_VALUE_NAME_EN,
    CODE_VALUE_DESCRIPTION, SORT_ORDER, DEFAULT_VALUE, DATA_END_STATUS
)
SELECT 'S', 'SYSTEM', 'V016_SEED', 'S', 'SYSTEM', 'V016_SEED',
       c.CODE_ID, seed.CODE_VALUE, seed.CODE_VALUE_NAME_KO, seed.CODE_VALUE_NAME_KO,
       seed.CODE_VALUE_NAME_EN, seed.CODE_VALUE_DESCRIPTION, seed.SORT_ORDER, NULL, 'N'
FROM TB_M26_CODE c
JOIN (
    SELECT 'HEATING' CODE_VALUE, '가열' CODE_VALUE_NAME_KO, 'Heating' CODE_VALUE_NAME_EN, 'Heating process' CODE_VALUE_DESCRIPTION, 10 SORT_ORDER
    UNION ALL SELECT 'ROLLING', '압연', 'Rolling', 'Rolling process', 20
    UNION ALL SELECT 'WIRE', '선재', 'Wire', 'Wire process', 30
    UNION ALL SELECT 'FINISHING', '정정', 'Finishing', 'Finishing process', 40
) seed
WHERE UPPER(c.CODE_NAME) = 'PROCESS_AREA'
  AND NOT EXISTS (SELECT 1 FROM TB_M26_CODE_DETAIL d WHERE d.CODE_ID = c.CODE_ID AND UPPER(d.CODE_VALUE) = seed.CODE_VALUE);

INSERT INTO TB_M26_MODEL_PROCESS (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    PROCESS_AREA_CODE, MODEL_NAME, AUTOMATION_NAME, SERVER_IP, PYTHON_PROJECT_PATH,
    PROCESS_STATUS, MONITORING_STATUS, CONTROL_STATUS, LAST_STATUS_TIMESTAMP, DESCRIPTION
)
SELECT 'S', 'SYSTEM', 'V016_SEED', 'S', 'SYSTEM', 'V016_SEED',
       seed.PROCESS_AREA_CODE, seed.MODEL_NAME, seed.AUTOMATION_NAME, seed.SERVER_IP,
       seed.PYTHON_PROJECT_PATH, seed.PROCESS_STATUS, seed.MONITORING_STATUS,
       seed.CONTROL_STATUS, seed.LAST_STATUS_TIMESTAMP, seed.DESCRIPTION
FROM (
    SELECT 'HEATING' PROCESS_AREA_CODE, '가열로 스키드 감시' MODEL_NAME, '가열로 이상감지' AUTOMATION_NAME, '10.20.4.21' SERVER_IP, '/opt/vision/heating/skid-monitor' PYTHON_PROJECT_PATH, 'RUNNING' PROCESS_STATUS, 'NORMAL' MONITORING_STATUS, 'NORMAL' CONTROL_STATUS, '2026-09-17 08:45:00' LAST_STATUS_TIMESTAMP, NULL DESCRIPTION
    UNION ALL SELECT 'ROLLING', '압연 오버 이상감지', '압연 이상감지', '10.20.4.22', '/opt/vision/rolling/equipment-monitor', 'RUNNING', 'NORMAL', 'FAILED', '2026-09-17 08:43:00', NULL
    UNION ALL SELECT 'WIRE', '선재 표면 결함감지', '선재 결함감지', '10.20.4.23', '/opt/vision/wire/surface-defect', 'ERROR', 'FAILED', 'CHECKING', '2026-09-17 08:40:00', NULL
    UNION ALL SELECT 'FINISHING', '정정 공정 엣지감시', '정정 엣지감시', '10.20.4.24', '/opt/vision/finishing/quality-monitor', 'STOPPED', 'UNKNOWN', 'NORMAL', NULL, NULL
) seed
WHERE NOT EXISTS (SELECT 1 FROM TB_M26_MODEL_PROCESS p WHERE p.PROCESS_AREA_CODE = seed.PROCESS_AREA_CODE AND p.MODEL_NAME = seed.MODEL_NAME AND p.DATA_END_STATUS = 'N');

INSERT INTO TB_M26_MODEL_EVENT_LOG (
    CREATED_OBJECT_TYPE, CREATED_OBJECT_ID, CREATED_PROGRAM_ID,
    LAST_UPDATED_OBJECT_TYPE, LAST_UPDATED_OBJECT_ID, LAST_UPDATED_PROGRAM_ID,
    MODEL_PROCESS_ID, OCCURRED_TIMESTAMP, SEVERITY, EVENT_TYPE, MESSAGE, DETECTION_SUMMARY
)
SELECT 'S', 'SYSTEM', 'V016_SEED', 'S', 'SYSTEM', 'V016_SEED', p.MODEL_PROCESS_ID,
       seed.OCCURRED_TIMESTAMP, seed.SEVERITY, seed.EVENT_TYPE, seed.MESSAGE, seed.DETECTION_SUMMARY
FROM TB_M26_MODEL_PROCESS p
JOIN (
    SELECT 'HEATING' PROCESS_AREA_CODE, '2026-09-17 08:45:00' OCCURRED_TIMESTAMP, 'INFO' SEVERITY, 'AGENT_HEARTBEAT' EVENT_TYPE, 'Python process heartbeat received' MESSAGE, 'alive=true' DETECTION_SUMMARY
    UNION ALL SELECT 'ROLLING', '2026-09-17 08:43:00', 'ERROR', 'CONTROL_CALL_FAILED', 'Control integration call failed', 'connection timeout'
    UNION ALL SELECT 'WIRE', '2026-09-17 08:40:00', 'WARNING', 'AGENT_HEARTBEAT_MISSED', 'Agent heartbeat missed', 'last-seen 5 minutes ago'
) seed ON seed.PROCESS_AREA_CODE = p.PROCESS_AREA_CODE
WHERE p.DATA_END_STATUS = 'N'
  AND NOT EXISTS (SELECT 1 FROM TB_M26_MODEL_EVENT_LOG l WHERE l.MODEL_PROCESS_ID = p.MODEL_PROCESS_ID AND l.EVENT_TYPE = seed.EVENT_TYPE AND l.OCCURRED_TIMESTAMP = seed.OCCURRED_TIMESTAMP AND l.DATA_END_STATUS = 'N');
