UPDATE TB_M26_CODE_DETAIL d
JOIN TB_M26_CODE c ON c.CODE_ID = d.CODE_ID
SET d.CODE_VALUE_NAME = CASE d.CODE_VALUE
        WHEN 'HEATING' THEN '가열'
        WHEN 'ROLLING' THEN '압연'
        WHEN 'WIRE' THEN '선재'
        WHEN 'FINISHING' THEN '정정'
        ELSE d.CODE_VALUE_NAME
    END,
    d.CODE_VALUE_NAME_KO = CASE d.CODE_VALUE
        WHEN 'HEATING' THEN '가열'
        WHEN 'ROLLING' THEN '압연'
        WHEN 'WIRE' THEN '선재'
        WHEN 'FINISHING' THEN '정정'
        ELSE d.CODE_VALUE_NAME_KO
    END
WHERE UPPER(c.CODE_NAME) = 'PROCESS_AREA'
  AND d.CODE_VALUE IN ('HEATING', 'ROLLING', 'WIRE', 'FINISHING');

UPDATE TB_M26_MODEL_PROCESS
SET MODEL_NAME = CASE PROCESS_AREA_CODE
        WHEN 'HEATING' THEN '가열로 스키드 감시'
        WHEN 'ROLLING' THEN '압연 오버 이상감지'
        WHEN 'WIRE' THEN '선재 표면 결함감지'
        WHEN 'FINISHING' THEN '정정 공정 엣지감시'
        ELSE MODEL_NAME
    END,
    AUTOMATION_NAME = CASE PROCESS_AREA_CODE
        WHEN 'HEATING' THEN '가열로 이상감지'
        WHEN 'ROLLING' THEN '압연 이상감지'
        WHEN 'WIRE' THEN '선재 결함감지'
        WHEN 'FINISHING' THEN '정정 엣지감시'
        ELSE AUTOMATION_NAME
    END
WHERE PROCESS_AREA_CODE IN ('HEATING', 'ROLLING', 'WIRE', 'FINISHING');

UPDATE TB_M26_MODEL_EVENT_LOG
SET MESSAGE = CASE EVENT_TYPE
        WHEN 'AGENT_HEARTBEAT' THEN 'Python 프로세스 heartbeat 수신'
        WHEN 'CONTROL_CALL_FAILED' THEN '제어 연동 호출 실패'
        WHEN 'AGENT_HEARTBEAT_MISSED' THEN 'Agent heartbeat 미수신'
        ELSE MESSAGE
    END
WHERE EVENT_TYPE IN ('AGENT_HEARTBEAT', 'CONTROL_CALL_FAILED', 'AGENT_HEARTBEAT_MISSED');
