UPDATE TB_M26_USER
SET ENCRYPTED_FOUNDATION_PASSWORD = '$2a$10$70rfwiK385TyvFbJpDftSe6xujiqgmulcvQ.YIS/RXMVtCy8sfrGq',
    LAST_UPDATED_OBJECT_TYPE = 'S',
    LAST_UPDATED_OBJECT_ID = 'SYSTEM',
    LAST_UPDATED_PROGRAM_ID = 'V019_PASSWORD',
    LAST_UPDATED_TIMESTAMP = CURRENT_TIMESTAMP()
WHERE USER_EMP_NO = 'tester'
  AND DATA_END_STATUS = 'N';
