ALTER TABLE TB_M26_USER
    ADD COLUMN USER_EMAIL VARCHAR(254) DEFAULT NULL,
    ADD COLUMN USER_PHONE VARCHAR(50) DEFAULT NULL;

CREATE TABLE TB_M26_USER_ALERT_PREF (
    CREATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    CREATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    CREATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    CREATED_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP(),
    LAST_UPDATED_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    LAST_UPDATED_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    LAST_UPDATED_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    DATA_END_STATUS VARCHAR(1) DEFAULT 'N',
    DATA_END_OBJECT_TYPE VARCHAR(1) DEFAULT NULL,
    DATA_END_OBJECT_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_PROGRAM_ID VARCHAR(22) DEFAULT NULL,
    DATA_END_TIMESTAMP DATETIME DEFAULT NULL,
    USER_ALERT_PREF_ID INT(15) UNSIGNED NOT NULL AUTO_INCREMENT,
    USER_ID INT(15) UNSIGNED NOT NULL,
    EMAIL_ENABLED VARCHAR(1) NOT NULL DEFAULT 'N',
    SMS_ENABLED VARCHAR(1) NOT NULL DEFAULT 'N',
    PRIMARY KEY (USER_ALERT_PREF_ID),
    UNIQUE KEY UK_M26_USER_ALERT_PREF_USER (USER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
